// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PatientsService.Infrastructure.Data;

#nullable disable

namespace PatientsService.Infrastructure.Migrations
{
    [DbContext(typeof(PatientsDbContext))]
    [Migration("20260609200000_AddConsultationLogs")]
    partial class AddConsultationLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
